/**
 * Interface representing the structure of the 'notebooks_isaiah_ella' table.
 */
interface NotebookIsaiahElla {
    /**
     * Unique identifier for the notebook.
     * Auto-generated by the database.
     * SQL type: bigint
     */
    readonly id: number; // Changed from bigint to number
  
    /**
     * Timestamp indicating when the notebook was created.
     * Defaults to the current time in the database.
     * SQL type: timestamp with time zone
     */
    readonly created_at: Date;
  
    /**
     * The name of the notebook.
     * SQL type: character varying (nullable)
     */
    name: string | null;
  
    /**
     * A description for the notebook.
     * SQL type: text (nullable)
     */
    description: string | null;
  
    /**
     * A color associated with the notebook (e.g., hex code or color name).
     * SQL type: character varying (nullable)
     */
    color: string | null;
  }
  
  /**
   * Interface representing the structure of the 'notes_isaiah_ella' table.
   */
  interface NoteIsaiahElla {
    /**
     * Unique identifier for the note.
     * Auto-generated by the database.
     * SQL type: bigint
     */
    readonly id: number; // Changed from bigint to number
  
    /**
     * Timestamp indicating when the note was created.
     * Defaults to the current time in the database.
     * SQL type: timestamp with time zone
     */
    readonly created_at: Date;
  
    /**
     * The main content of the note.
     * SQL type: text (nullable)
     */
    contents: string | null;
  
    /**
     * Foreign key referencing the 'id' of the notebook this note belongs to.
     * If null, the note might not be associated with any specific notebook.
     * SQL type: bigint (nullable)
     */
    notebook_id: number | null; // Changed from bigint | null to number | null
  }