create table public.ella_adjectives (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  adjective text not null,
  adverb text null default 'so'::text,
  constraint ella_adjectives_pkey primary key (id),
  constraint ella_adjectives_adjective_key unique (adjective)
) TABLESPACE pg_default;

create table public.notebooks_isaiah_ella (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying null,
  description text null,
  color character varying null,
  constraint notebooks_isaiah_ella_pkey primary key (id)
) TABLESPACE pg_default;

create table public.notes_isaiah_ella (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  contents text null,
  notebook_id bigint null,
  constraint notes_isaiah_ella_pkey primary key (id),
  constraint notes_isaiah_ella_notebook_id_fkey foreign KEY (notebook_id) references notebooks_isaiah_ella (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.meetup_dates_isaiah_ella (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "when" timestamp with time zone not null,
  constraint meetup_dates_isaiah_ella_pkey primary key (id),
  constraint meetup_dates_isaiah_ella_when_key unique ("when")
) TABLESPACE pg_default;